name: C/C++ CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3

    - name: apt
      run: sudo apt update && sudo apt install c1541 moreutils libfreeimageplus-dev

    - name: install llvm-mos
      run: |
        wget -q -O - https://github.com/llvm-mos/llvm-mos-sdk/releases/latest/download/llvm-mos-linux.tar.xz | tar xJf - -C $HOME

    #- name: Setup upterm session
    #  uses: lhotari/action-upterm@v1
    #  with:
    #    limit-access-to-actor: true

    - name: make
      run: make LLVM=$HOME/llvm-mos/bin

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}.${{ github.sha }}
        path: |
          ptracker.prg
          ptracker.d64
